version: '2'

services:
    app:
        build:
            context: .
            dockerfile: docker-dir/Dockerfile
        ports:
            - "8080:8080"
            - "9990:9990"
        volumes:
            - ./data:/data